name: Flutter Web Only Build

on:
  workflow_dispatch:

jobs:
  run-flutter-ios-build:
    uses: ./.github/workflows/flutter-build-web.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "custom"
